# Generated by Django 3.2.8 on 2021-12-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ic',
            field=models.CharField(help_text='Enter 12 digits ic number', max_length=12, unique=True, verbose_name='IC Number'),
        ),
    ]
