# Generated by Django 3.2.8 on 2021-12-29 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('ic', models.CharField(default='', max_length=255, verbose_name='Ic')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=3, null=True, verbose_name='Progress Percentage')),
                ('victim_number', models.IntegerField(verbose_name='Victim Number')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('assistance_given_date', models.DateField(null=True, verbose_name='Assistance Given Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('assistance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_type', to='assistance_app.assistancetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
