# Generated by Django 3.2.8 on 2022-01-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('victim_app', '0002_auto_20220102_0700'),
        ('assistance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='user',
        ),
        migrations.AddField(
            model_name='assistance',
            name='victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_list', to='victim_app.victim'),
        ),
    ]
