# Generated by Django 3.2.8 on 2021-12-29 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('is_kir', models.BooleanField(default=True, verbose_name='Ketua Isi Rumah')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary')),
                ('address1', models.CharField(max_length=255, verbose_name='Address1')),
                ('address2', models.CharField(max_length=255, verbose_name='Address2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('mukim', models.CharField(max_length=255, verbose_name='Mukim')),
                ('parlimen', models.CharField(max_length=255, verbose_name='Parlimen')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('poskod', models.CharField(max_length=255, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
