# Generated by Django 3.2.8 on 2022-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victim_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic', models.CharField(help_text='Enter 12 digits ic number', max_length=12, unique=True, verbose_name='IC Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('is_kir', models.BooleanField(default=True, verbose_name='Ketua Isi Rumah')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary')),
                ('address1', models.CharField(max_length=255, verbose_name='Address1')),
                ('address2', models.CharField(max_length=255, verbose_name='Address2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('mukim', models.CharField(max_length=255, verbose_name='Mukim')),
                ('parlimen', models.CharField(max_length=255, verbose_name='Parlimen')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('poskod', models.CharField(max_length=255, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
